//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TranHoangDinh_2120110042.Context
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class Category
    {
        public int CateId { get; set; }
        public string CateName { get; set; }
        public string CateImage { get; set; }
        public string CateSlug { get; set; }
        public Nullable<bool> CateShowOnHomePage { get; set; }
        public Nullable<int> CateDisplayOrder { get; set; }
        public Nullable<bool> CateDeleted { get; set; }
        public Nullable<System.DateTime> CateCreatedOnUtc { get; set; }
        public Nullable<System.DateTime> CateUpdatedOnUtc { get; set; }
        public HttpPostedFileBase ImageUpload { get; set; }
    }
}
