//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TranHoangDinh_2120110042.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public int OrderDetailid { get; set; }
        public int OrderIdDe { get; set; }
        public int ProductIdDe { get; set; }
        public int Quantity { get; set; }
    }
}
